spring:
  application:
    name: customerdata
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/achieversoft
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


#server:
#  servlet:
#    contextPath: /ecommapp


